name: better_u
description: "A new Flutter project."
publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.7.0
  flutter_svg: ^2.0.16
  shared_preferences: ^2.3.3
  get: ^4.6.6
  smooth_page_indicator: ^1.2.0+3
  carousel_slider: ^5.0.0
  intl: ^0.20.1
  image_picker: ^1.1.2
  pinput: ^5.0.0
  url_launcher: ^6.3.1
  bottom_picker: ^2.9.0
  loading_animation_widget: ^1.2.1
  modal_bottom_sheet: ^3.0.0
  http: ^1.2.2
  dropdown_button2: ^2.3.9
  shimmer: ^3.0.0
  flutter_dotenv: ^5.2.1


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/svg/
    - assets/image/
    - assets/gif/
    - .env

  fonts:
    - family: Montserrat
      fonts:
        - asset: assets/font/Montserrat-Black.ttf
        - asset: assets/font/Montserrat-Bold.ttf
        - asset: assets/font/Montserrat-ExtraBold.ttf
        - asset: assets/font/Montserrat-Light.ttf
        - asset: assets/font/Montserrat-Medium.ttf
        - asset: assets/font/Montserrat-Regular.ttf
        - asset: assets/font/Montserrat-SemiBold.ttf
        - asset: assets/font/Montserrat-Thin.ttf

